development:
  app_id: '270593390367436'
  app_secret: '4039f8bc030756e1f7cae6268d4d637b'
  callback_url: 'http://localhost:3000/auth/facebook/callback'

production:
  app_id: '270593390367436'
  app_secret: '4039f8bc030756e1f7cae6268d4d637b'
  callback_url: 'https://app.3wrongs.com/auth/facebook/callback'  